---
title: "Analysis of simulations"
format: html
editor: visual
---

```{r}

library(tidyverse)
library(glue)

```

```{r}

tab <- tibble()
for (i in 1:3) {
  for (j in 0:9) {
    tab <- bind_rows(tab, 
                     read_csv(glue('../results/tab_{j}_{i}_{i}.csv'), 
                              col_names = FALSE,
                              show_col_types = FALSE) %>% 
                       mutate(n = i, rep = j))
  }
}

```

```{r}

tab %>% 
  ggplot() +
  geom_line(aes(X1, X9, color = as.character(rep))) +
  facet_grid(rep~n, scales = 'free')

```


```{r}

labs <- tab %>% 
  filter(X1 == -1, n == 1, rep == 0) %>% 
  pivot_longer(starts_with('X')) %>% 
  filter(name != 'X9')

labs_2 <- tab %>% 
  filter(X1 == 0) %>% 
  pivot_longer(starts_with('X')) %>% 
  filter(name != 'X9')

tab %>% 
  filter(X1 != -1) %>% 
  group_by(n, rep) %>% 
  filter(X9 == max(X9)) %>% 
  top_n(1, -X1) %>% 
  pivot_longer(starts_with('X')) %>% 
  ggplot() +
  geom_boxplot(aes(n, value, group = n)) +
  geom_text(aes(n, value, label = rep), position = 'jitter') +
  geom_hline(aes(yintercept = value), data = labs, color = 'red') +
  geom_hline(aes(yintercept = value), data = labs_2, color = 'blue') +
  facet_wrap(~name, scales = 'free')

```



